uxnsolve: no colours if stdout is not a tty

diff --git a/uxnsolve b/uxnsolve
--- a/uxnsolve
+++ b/uxnsolve
@@ -19,13 +19,19 @@ case "$1" in
     ;;
 esac
 
+[ -t 1 ] && {
+    red="\033[1;31m"
+    yellow="\033[1;33m"
+    reset="\033[m"
+}
+
 debug_file="$1"
 source_file="${1%.debug}"
 
 check_versions() {
     read -r v < "$1"
     if [ "$v" != "$VERSION" ]; then
-        printf "\033[1;33mERROR\033[m: incompatible version '%s' (this tool is version %d)\n" "$v" "$VERSION" >&2
+        printf "${yellow}ERROR${reset}: incompatible version '%s' (this tool is version %d)\n" "$v" "$VERSION" >&2
         exit 1
     fi
 }
@@ -34,7 +40,7 @@ compare_file_timestamps() {
     # TODO: recurse through included files to check timestamps
     case "$(ls -t "$1" "$1.debug")" in
         "$1.debug"*) ;;
-        *) printf "\033[1;33mWARNING\033[m: source file is newer than debug info\n" >&2 ;;
+        *) printf "${yellow}WARNING${reset}: source file is newer than debug info\n" >&2 ;;
     esac
 }
 
@@ -68,7 +74,7 @@ print_highlighted() {
     j=1
     for tok; do
         if [ "$j" -eq "$index" ]; then
-            printf " \033[1;31m%s\033[m" "$tok"
+            printf " ${red}%s${reset}" "$tok"
         else
             printf " %s" "$tok"
         fi
